server:
  port: 8090

spring:
  application:
    name: student-service
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/Library
      username: postgres
      password: postgres2019
  jpa:
      hibernate:
        ddl-auto: none
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
